# Generated by Django 5.1.7 on 2025-04-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
